### ISSUE TITLE
프로젝트 생성

### ISSUE THREAD

**Issue by harryjeonn** [Kkosunae/backend#1]
## 할일
- [x]  Nest.js 프로젝트 생성
- [x] Package manager는 npm으로 셋팅

## 공유할 내용
Framework는 Nest.js 로 결정
- 이유는 ? typescript쓸거면 nest.js 가 낫다고 생각함. node 에서 type쓰는건 안해봤고 셋팅할때 까다로울거같음 ..

**Comment by ssowon** [comment]
* Nest.js 프로젝트를 생성하여 push 완료
* 프로젝트 매니저는 npm으로 셋팅
